spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4001/jimmer_demo
    username: root
    password: 123456
  redis:
    host: localhost
    port: 4004
  kafka:
    consumer:
      bootstrap-servers: localhost:4003
      group-id: jimmer-demo/sql
      enable-auto-commit: false
    listener:
      ack-mode: MANUAL